#!/usr/bin/env python3
"""Download CREMA-D and build the E1 manifests (speaker-disjoint and random-split).

CREMA-D is ODbL-licensed and redistributable, but at 470 MB we don't commit the
audio -- this script fetches it into the gitignored `data/cremad/` cache. The
manifests it produces are reproducible (deterministic given the tarball and the
pinned seed), so they too are gitignored and regenerated by `make data`.

Usage:
    uv run python scripts/fetch_cremad.py
"""

from __future__ import annotations

import logging
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

import pandas as pd
from tqdm import tqdm

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from ssa.manifest import add_congruence, write_manifest  # noqa: E402
from ssa.mapping import map_emotion  # noqa: E402
from ssa.splits import random_split, speaker_disjoint_split  # noqa: E402
from ssa.types import Sentiment  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# Pinned in CLAUDE.md: ungated HF mirror of the original ODbL-licensed CREMA-D.
TARBALL_URL = "https://huggingface.co/datasets/myleslinder/crema-d/resolve/main/data/crema_d.tar.gz"
EXPECTED_CLIP_COUNT = 7_442
EXPECTED_SPEAKER_COUNT = 91

CACHE_DIR = REPO_ROOT / "data" / "cache"
OUT_DIR = REPO_ROOT / "data" / "cremad"
TARBALL_PATH = CACHE_DIR / "crema_d.tar.gz"
AUDIO_DIR = OUT_DIR / "AudioWAV"

# The 12 fixed carrier sentences, verified against the CREMA-D README. All are
# emotionally neutral by design -- hence text_sentiment is NEUTRAL for every
# CREMA-D row, regardless of the acted emotion (prosody_sentiment).
SENTENCE_TEXT: dict[str, str] = {
    "IEO": "It's eleven o'clock",
    "TIE": "That is exactly what happened",
    "IOM": "I'm on my way to the meeting",
    "IWW": "I wonder what this is about",
    "TAI": "The airplane is almost full",
    "MTI": "Maybe tomorrow it will be cold",
    "IWL": "I would like a new alarm clock",
    "ITH": "I think I have a doctor's appointment",
    "DFA": "Don't forget a jacket",
    "ITS": "I think I've seen this before",
    "TSI": "The surface is slick",
    "WSI": "We'll stop in a couple of minutes",
}

_FILENAME_RE = re.compile(
    # Intensity is normally 2 chars (XX/HI/LO/MD) but the real distribution
    # contains at least one truncated code (1040_ITH_SAD_X.wav) -- we don't
    # use the intensity field, so accept 1-2 chars rather than drop an
    # otherwise validly-labelled clip.
    r"^(?P<speaker>\d{4})_(?P<sentence>[A-Z]{3,4})_(?P<emotion>[A-Z]{3})_(?P<intensity>[A-Z0-9]{1,2})\.wav$"
)

SPLIT_SEED = 0


class CremaDFetchError(RuntimeError):
    pass


def _download(url: str, dest: Path) -> None:
    if dest.exists() and dest.stat().st_size > 0:
        logger.info("using cached tarball: %s (%.1f MB)", dest, dest.stat().st_size / 1e6)
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".partial")
    logger.info("downloading %s", url)

    with urllib.request.urlopen(url) as resp:
        total = int(resp.headers.get("Content-Length", 0))
        with (
            open(tmp, "wb") as f,
            tqdm(total=total, unit="B", unit_scale=True, desc="crema_d.tar.gz") as bar,
        ):
            while chunk := resp.read(1 << 20):
                f.write(chunk)
                bar.update(len(chunk))
    tmp.rename(dest)


def _extract(tarball: Path, out_dir: Path) -> None:
    existing = list(out_dir.glob("AudioWAV/*.wav")) if out_dir.exists() else []
    if len(existing) == EXPECTED_CLIP_COUNT:
        logger.info("already extracted: %d wav files present", len(existing))
        return
    logger.info("extracting %s -> %s", tarball, out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    with tarfile.open(tarball, "r:gz") as tf:
        members = [m for m in tf.getmembers() if m.name.endswith(".wav")]
        for m in tqdm(members, desc="extracting"):
            # tar entries are "data/AudioWAV/<file>.wav"; flatten to AudioWAV/<file>.wav
            m.name = str(Path(*Path(m.name).parts[-2:]))
            tf.extract(m, out_dir, filter="data")


def _parse_filename(wav_path: Path) -> dict[str, str]:
    m = _FILENAME_RE.match(wav_path.name)
    if m is None:
        raise CremaDFetchError(f"unexpected filename format: {wav_path.name}")
    return m.groupdict()


def _build_rows(audio_dir: Path) -> pd.DataFrame:
    wavs = sorted(audio_dir.glob("*.wav"))
    if not wavs:
        raise CremaDFetchError(f"no wav files found in {audio_dir}")

    records = []
    skipped: list[str] = []
    for wav in wavs:
        try:
            fields = _parse_filename(wav)
        except CremaDFetchError as exc:
            skipped.append(str(exc))
            continue

        sentence_code = fields["sentence"]
        if sentence_code not in SENTENCE_TEXT:
            skipped.append(f"{wav.name}: unknown sentence code {sentence_code!r}")
            continue

        try:
            prosody_sentiment = map_emotion(fields["emotion"], "crema_d")
        except (KeyError, ValueError) as exc:
            skipped.append(f"{wav.name}: {exc}")
            continue

        records.append(
            {
                "clip_id": f"cremad_{wav.stem}",
                "path": str(wav.relative_to(REPO_ROOT)),
                "speaker_id": fields["speaker"],
                "source": "crema_d",
                "text": SENTENCE_TEXT[sentence_code],
                "text_sentiment": Sentiment.NEUTRAL.value,
                "prosody_sentiment": prosody_sentiment.value,
                "emotion_tag": fields["emotion"],
                "voice_id": "",
            }
        )

    if skipped:
        # Fail loudly rather than silently dropping clips (CLAUDE.md rule).
        raise CremaDFetchError(
            f"{len(skipped)} clip(s) could not be parsed/labelled, e.g.:\n"
            + "\n".join(skipped[:10])
        )

    df = pd.DataFrame.from_records(records)
    df = add_congruence(df)
    return df


def main() -> None:
    _download(TARBALL_URL, TARBALL_PATH)
    _extract(TARBALL_PATH, OUT_DIR)

    df = _build_rows(AUDIO_DIR)
    n_speakers = df["speaker_id"].nunique()
    logger.info("parsed %d clips from %d speakers", len(df), n_speakers)

    if len(df) != EXPECTED_CLIP_COUNT:
        raise CremaDFetchError(f"expected {EXPECTED_CLIP_COUNT} clips, got {len(df)}")
    if n_speakers != EXPECTED_SPEAKER_COUNT:
        raise CremaDFetchError(f"expected {EXPECTED_SPEAKER_COUNT} speakers, got {n_speakers}")

    disjoint = speaker_disjoint_split(df, test_frac=0.2, val_frac=0.1, seed=SPLIT_SEED)
    write_manifest(disjoint, OUT_DIR / "manifest.csv")

    leaky = random_split(df, test_frac=0.2, val_frac=0.1, seed=SPLIT_SEED)
    write_manifest(leaky, OUT_DIR / "manifest_randomsplit.csv")

    logger.info("done: %s", OUT_DIR)


if __name__ == "__main__":
    main()
